### PR TITLE
Add MIT License

### PR DESCRIPTION
**Pull request by kduncklee**
Release BAMRU.net as open source under the MIT License.

### CODE REVIEW

**Comment by kduncklee** [comment]
Please comment if you approve. When everyone approves, we can merge.

**Comment by genev** [comment]
Approved. 

Do we plan to write up documentation on how to set things up from scratch?

**Comment by jboning** [comment]
Approved!

**Comment by kduncklee** [comment]
> Do we plan to write up documentation on how to set things up from scratch?

Yes, I'd like to have this. A simple demo database file would also ease development.

**Comment by ctaylor451** [comment]
Fine by me

**Review by ctaylor451 — APPROVED** [review]
Approved

**Pull request merged**
