### PR TITLE
Added Info and Broadcast paging. Fixed issues #148 and #149

### PR DESCRIPTION
**Pull request by ctaylor451**

### CODE REVIEW

**Comment by ctaylor451** [comment]
What should the rsvp_template be for info and broadcast?  Added a test for None but having an empty template seems like it might be better

**Comment by kduncklee** [comment]
> What should the rsvp_template be for info and broadcast? Added a test for None but having an empty template seems like it might be better

I think using None is fine. It makes it more clear when doing the HTML template with links.

**Comment by kduncklee** [comment]
> You have a try clause that will fail and report a logger error, if you care
I only see this for the re-page. Is there another?

**Comment by ctaylor451** [comment]
I think line 79 in message_view will log an error, haven't verify it

**Pull request merged**
